name: python_environment
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.4
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - torchvision=0.14.0
  - pip=22.3.1
  - numpy=1.24.3
  - matplotlib=3.7.1
  - pip:
    - opencv-python
    - imutils==0.5.4
    - timm==0.6.12
    - einops==0.6.0
    - scipy
    - pysolotools==0.3.17
    - pycocotools==2.0.7
    - openexr